apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APPLICATION-NAME-app
spec:
  tls:
    - hosts:
      - APPLICATION-HOSTS-FQDN
      secretName: APPLICATION-HOSTS-FQDN-tls
  rules:
  - host: APPLICATION-HOSTS-FQDN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: APPLICATION-NAME-app
            port: 
              number: 8000