# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: PVC_NAME-pv
# spec:
#   capacity:
#     storage: 1Ti
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: PVC_SERVER
#     path: PVC_PATH
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: PVC_NAME-pvc
  namespace: thl2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
